[build]
  command = "npm install && npm run build"  # Substitua "build" pelo nome do seu script de build, se necessário
  functions = "functions"  # Diretório onde suas funções serverless serão armazenadas

[dev]
  functions = "functions"  # Diretório das funções para ambiente de desenvolvimento
