export const pokemons_db = [
  {
    nome: "Pikachu",
    habilidades: ["Static", "Lightning Rod"],
    tipo: ["Elétrico"],
    fraquezas: ["Terra"],
  },
  {
    nome: "Charizard",
    habilidades: ["Blaze", "Solar Power"],
    tipo: ["Fogo", "Voador"],
    fraquezas: ["Água", "Elétrico", "Rocha"],
  },
  {
    nome: "Bulbasaur",
    habilidades: ["Overgrow", "Chlorophyll"],
    tipo: ["Planta", "Veneno"],
    fraquezas: ["Fogo", "Psíquico", "Gelo", "Voador"],
  },
  {
    nome: "Machop",
    habilidades: ["Guts", "No Guard"],
    tipo: ["Lutador"],
    fraquezas: ["Voador", "Psíquico", "Fada"],
  },
  {
    nome: "Squirtle",
    habilidades: ["Torrent", "Rain Dish"],
    tipo: ["Água"],
    fraquezas: ["Elétrico", "Planta"],
  },
  {
    nome: "Eevee",
    habilidades: ["Adaptability", "Run Away"],
    tipo: ["Normal"],
    fraquezas: ["Lutador"],
  },
  {
    nome: "Snorlax",
    habilidades: ["Immunity", "Thick Fat"],
    tipo: ["Normal"],
    fraquezas: ["Lutador"],
  },
  {
    nome: "Gengar",
    habilidades: ["Levitate", "Cursed Body"],
    tipo: ["Fantasma", "Venenoso"],
    fraquezas: ["Psíquico", "Terra"],
  },
  {
    nome: "Dragonite",
    habilidades: ["Inner Focus", "Multiscale"],
    tipo: ["Dragão", "Voador"],
    fraquezas: ["Gelo", "Dragão", "Fada"],
  },
  {
    nome: "Mewtwo",
    habilidades: ["Pressure", "Unnerve"],
    tipo: ["Psíquico"],
    fraquezas: ["Inseto", "Fantasma", "Noturno"],
  },
  {
    nome: "Lucario",
    habilidades: ["Steadfast", "Inner Focus"],
    tipo: ["Lutador", "Aço"],
    fraquezas: ["Fogo", "Lutador", "Solo"],
  },
  {
    nome: "Gyarados",
    habilidades: ["Intimidate", "Moxie"],
    tipo: ["Água", "Voador"],
    fraquezas: ["Elétrico", "Rocha"],
  },
  {
    nome: "Gardevoir",
    habilidades: ["Synchronize", "Trace"],
    tipo: ["Psíquico", "Fada"],
    fraquezas: ["Aço", "Veneno"],
  },
  {
    nome: "Salamence",
    habilidades: ["Intimidate", "Moxie"],
    tipo: ["Dragão", "Voador"],
    fraquezas: ["Gelo", "Dragão", "Rocha"],
  },
  {
    nome: "Alakazam",
    habilidades: ["Synchronize", "Inner Focus"],
    tipo: ["Psíquico"],
    fraquezas: ["Inseto", "Fantasma", "Noturno"],
  },
  {
    nome: "Venusaur",
    habilidades: ["Overgrow", "Chlorophyll"],
    tipo: ["Planta", "Venenoso"],
    fraquezas: ["Fogo", "Psíquico", "Gelo", "Voador"],
  },
  {
    nome: "Machamp",
    habilidades: ["Guts", "No Guard"],
    tipo: ["Lutador"],
    fraquezas: ["Voador", "Psíquico", "Fada"],
  },
  {
    nome: "Mew",
    habilidades: ["Synchronize"],
    tipo: ["Psíquico"],
    fraquezas: ["Inseto", "Fantasma", "Noturno"],
  },
  {
    nome: "Blastoise",
    habilidades: ["Torrent", "Rain Dish"],
    tipo: ["Água"],
    fraquezas: ["Elétrico", "Planta"],
  },
  {
    nome: "Garchomp",
    habilidades: ["Sand Veil", "Rough Skin"],
    tipo: ["Dragão", "Terra"],
    fraquezas: ["Gelo", "Dragão", "Fada"],
  },
  {
    nome: "Aerodactyl",
    habilidades: ["Rock Head", "Pressure"],
    tipo: ["Rocha", "Voador"],
    fraquezas: ["Água", "Elétrico", "Gelo", "Rocha", "Aço"],
  },
  {
    nome: "Jolteon",
    habilidades: ["Volt Absorb", "Quick Feet"],
    tipo: ["Elétrico"],
    fraquezas: ["Terra"],
  },
  {
    nome: "Arcanine",
    habilidades: ["Intimidate", "Flash Fire"],
    tipo: ["Fogo"],
    fraquezas: ["Água", "Terra", "Rocha"],
  },
  {
    nome: "Machoke",
    habilidades: ["Guts", "No Guard"],
    tipo: ["Lutador"],
    fraquezas: ["Voador", "Psíquico", "Fada"],
  },
  {
    nome: "Machop",
    habilidades: ["Guts", "No Guard"],
    tipo: ["Lutador"],
    fraquezas: ["Voador", "Psíquico", "Fada"],
  },
  {
    nome: "Vaporeon",
    habilidades: ["Water Absorb", "Hydration"],
    tipo: ["Água"],
    fraquezas: ["Elétrico", "Planta"],
  },
  {
    nome: "Golem",
    habilidades: ["Rock Head", "Sturdy"],
    tipo: ["Rocha", "Terra"],
    fraquezas: ["Água, Grama, Gelo, Lutador, Aço"],
  },
  {
    nome: "Onix",
    habilidades: ["Rock Head", "Sturdy"],
    tipo: ["Rocha", "Terra"],
    fraquezas: ["Água, Grama, Gelo, Lutador, Aço"],
  },
  {
    nome: "Lapras",
    habilidades: ["Water Absorb", "Shell Armor"],
    tipo: ["Água", "Gelo"],
    fraquezas: ["Lutador", "Elétrico", "Planta", "Pedra"],
  },
  {
    nome: "Ditto",
    habilidades: ["Limber", "Imposter"],
    tipo: ["Normal"],
    fraquezas: ["Lutador"],
  },
  {
    nome: "Vileplume",
    habilidades: ["Chlorophyll", "Effect Spore"],
    tipo: ["Planta", "Venenoso"],
    fraquezas: ["Fogo, Psíquico, Gelo, Voador"],
  },
  {
    nome: "Ninetales",
    habilidades: ["Flash Fire", "Drought"],
    tipo: ["Fogo", "Gelo"],
    fraquezas: ["Água, Lutador, Rocha, Aço"],
  },
  {
    nome: "Muk",
    habilidades: ["Stench", "Sticky Hold"],
    tipo: ["Venenoso"],
    fraquezas: ["Psíquico, Terra"],
  },
  {
    nome: "Marowak",
    habilidades: ["Lightning Rod", "Rock Head"],
    tipo: ["Solo"],
    fraquezas: ["Água, Grama, Gelo"],
  },
  {
    nome: "Gyarados",
    habilidades: ["Intimidate", "Moxie"],
    tipo: ["Água", "Voador"],
    fraquezas: ["Elétrico, Rocha"],
  },
  {
    nome: "Pidgeot",
    habilidades: ["Keen Eye", "Tangled Feet"],
    tipo: ["Normal", "Voador"],
    fraquezas: ["Elétrico, Gelo, Rocha"],
  },
  {
    nome: "Scyther",
    habilidades: ["Swarm", "Technician"],
    tipo: ["Inseto", "Voador"],
    fraquezas: ["Fogo, Elétrico, Gelo, Pedra"],
  },
  {
    nome: "Kadabra",
    habilidades: ["Synchronize", "Inner Focus"],
    tipo: ["Psíquico"],
    fraquezas: ["Inseto, Fantasma, Noturno"],
  },
  {
    nome: "Golem",
    habilidades: ["Rock Head", "Sturdy"],
    tipo: ["Rocha", "Terra"],
    fraquezas: ["Água, Grama, Gelo, Lutador, Aço"],
  },
  {
    nome: "Machop",
    habilidades: ["Guts", "No Guard"],
    tipo: ["Lutador"],
    fraquezas: ["Voador, Psíquico, Fada"],
  },
  {
    nome: "Vaporeon",
    habilidades: ["Water Absorb", "Hydration"],
    tipo: ["Água"],
    fraquezas: ["Elétrico, Planta"],
  },
  {
    nome: "Blastoise",
    habilidades: ["Torrent", "Rain Dish"],
    tipo: ["Água"],
    fraquezas: ["Elétrico, Planta"],
  },
  {
    nome: "Arcanine",
    habilidades: ["Intimidate", "Flash Fire"],
    tipo: ["Fogo"],
    fraquezas: ["Água, Terra, Rocha"],
  },
  {
    nome: "Lapras",
    habilidades: ["Water Absorb", "Shell Armor"],
    tipo: ["Água", "Gelo"],
    fraquezas: ["Lutador, Elétrico, Planta, Rocha"],
  },
  {
    nome: "Mewtwo",
    habilidades: ["Pressure", "Unnerve"],
    tipo: ["Psíquico"],
    fraquezas: ["Inseto, Fantasma, Noturno"],
  },
  {
    nome: "Aerodactyl",
    habilidades: ["Rock Head", "Pressure"],
    tipo: ["Rocha", "Voador"],
    fraquezas: ["Água, Elétrico, Gelo, Rocha, Aço"],
  },
  {
    nome: "Jolteon",
    habilidades: ["Volt Absorb", "Quick Feet"],
    tipo: ["Elétrico"],
    fraquezas: ["Terra"],
  },
  {
    nome: "Gengar",
    habilidades: ["Levitate", "Cursed Body"],
    tipo: ["Fantasma", "Venenoso"],
    fraquezas: ["Psíquico, Terra"],
  },
  {
    nome: "Rhydon",
    habilidades: ["Lightning Rod", "Rock Head"],
    tipo: ["Terra", "Rocha"],
    fraquezas: ["Água, Grama, Gelo, Lutador, Terra, Aço"],
  },
  {
    nome: "Machoke",
    habilidades: ["Guts", "No Guard"],
    tipo: ["Lutador"],
    fraquezas: ["Voador, Psíquico, Fada"],
  },
  {
    nome: "Pidgeotto",
    habilidades: ["Keen Eye", "Tangled Feet"],
    tipo: ["Normal", "Voador"],
    fraquezas: ["Elétrico, Gelo, Rocha"],
  },
  {
    nome: "Venusaur",
    habilidades: ["Overgrow", "Chlorophyll"],
    tipo: ["Planta", "Venenoso"],
    fraquezas: ["Fogo, Psíquico, Gelo, Voador"],
  },
  {
    nome: "Gyarados",
    habilidades: ["Intimidate", "Moxie"],
    tipo: ["Água", "Voador"],
    fraquezas: ["Elétrico, Rocha"],
  },
];
