export const pokemons_db = [
  {
    nome: "Pikachu",
    habilidades: ["Static", "Lightning Rod"],
    tipo: ["Elétrico"],
    fraquezas: ["Terra"],
    altura: 0.4,
    peso: 6,
    evolucao: "Raichu",
  },
  {
    nome: "Charizard",
    habilidades: ["Blaze", "Solar Power"],
    tipo: ["Fogo", "Voador"],
    fraquezas: ["Água", "Elétrico", "Rocha"],
    altura: 1.7,
    peso: 90.5,
    evolucao: "Charmander",
  },
  {
    nome: "Bulbasaur",
    habilidades: ["Overgrow", "Chlorophyll"],
    tipo: ["Planta", "Veneno"],
    fraquezas: ["Fogo", "Psíquico", "Gelo", "Voador"],
    altura: 0.7,
    peso: 6.9,
    evolucao: "Ivysaur",
  },
  {
    nome: "Machop",
    habilidades: ["Guts", "No Guard"],
    tipo: ["Lutador"],
    fraquezas: ["Voador", "Psíquico", "Fada"],
    altura: 0.8,
    peso: 19.5,
    evolucao: "Machoke",
  },
  {
    nome: "Squirtle",
    habilidades: ["Torrent", "Rain Dish"],
    tipo: ["Água"],
    fraquezas: ["Elétrico", "Planta"],
    altura: 0.5,
    peso: 9,
    evolucao: "Wartortle",
  },
  {
    nome: "Eevee",
    habilidades: ["Adaptability", "Run Away"],
    tipo: ["Normal"],
    fraquezas: ["Lutador"],
    altura: 0.3,
    peso: 6.5,
    evolucao:
      "Vaporeon, Jolteon, Flareon, Espeon, Umbreon, Leafeon, Glaceon, Sylveon",
  },
  {
    nome: "Snorlax",
    habilidades: ["Immunity", "Thick Fat"],
    tipo: ["Normal"],
    fraquezas: ["Lutador"],
    altura: 2.1,
    peso: 460,
    evolucao: "Munchlax",
  },
  {
    nome: "Gengar",
    habilidades: ["Levitate", "Cursed Body"],
    tipo: ["Fantasma", "Venenoso"],
    fraquezas: ["Psíquico", "Terra"],
    altura: 1.5,
    peso: 40.5,
    evolucao: "Haunter",
  },
  {
    nome: "Dragonite",
    habilidades: ["Inner Focus", "Multiscale"],
    tipo: ["Dragão", "Voador"],
    fraquezas: ["Gelo", "Dragão", "Fada"],
    altura: 2.2,
    peso: 210,
    evolucao: "Dragonair",
  },
  {
    nome: "Mewtwo",
    habilidades: ["Pressure", "Unnerve"],
    tipo: ["Psíquico"],
    fraquezas: ["Inseto", "Fantasma", "Noturno"],
    altura: 2,
    peso: 122,
    evolucao: "Mew",
  },
  {
    nome: "Lucario",
    habilidades: ["Steadfast", "Inner Focus"],
    tipo: ["Lutador", "Aço"],
    fraquezas: ["Fogo", "Lutador", "Solo"],
    altura: 1.2,
    peso: 54,
    evolucao: "Riolu",
  },
  {
    nome: "Gyarados",
    habilidades: ["Intimidate", "Moxie"],
    tipo: ["Água", "Voador"],
    fraquezas: ["Elétrico", "Rocha"],
    altura: 6.5,
    peso: 235,
    evolucao: "Magikarp",
  },
  {
    nome: "Gardevoir",
    habilidades: ["Synchronize", "Trace"],
    tipo: ["Psíquico", "Fada"],
    fraquezas: ["Aço", "Veneno"],
    altura: 1.6,
    peso: 48.4,
    evolucao: "Kirlia",
  },
  {
    nome: "Salamence",
    habilidades: ["Intimidate", "Moxie"],
    tipo: ["Dragão", "Voador"],
    fraquezas: ["Gelo", "Dragão", "Rocha"],
    altura: 1.5,
    peso: 102.6,
    evolucao: "Shelgon",
  },
  {
    nome: "Alakazam",
    habilidades: ["Synchronize", "Inner Focus"],
    tipo: ["Psíquico"],
    fraquezas: ["Inseto", "Fantasma", "Noturno"],
    altura: 1.5,
    peso: 48,
    evolucao: "Kadabra",
  },
  {
    nome: "Venusaur",
    habilidades: ["Overgrow", "Chlorophyll"],
    tipo: ["Planta", "Venenoso"],
    fraquezas: ["Fogo", "Psíquico", "Gelo", "Voador"],
    altura: 2,
    peso: 100,
    evolucao: "Ivysaur",
  },
  {
    nome: "Machamp",
    habilidades: ["Guts", "No Guard"],
    tipo: ["Lutador"],
    fraquezas: ["Voador", "Psíquico", "Fada"],
    altura: 1.6,
    peso: 130,
    evolucao: "Machoke",
  },
  {
    nome: "Mew",
    habilidades: ["Synchronize"],
    tipo: ["Psíquico"],
    fraquezas: ["Inseto", "Fantasma", "Noturno"],
    altura: 0.4,
    peso: 4,
    evolucao: null,
  },
  {
    nome: "Blastoise",
    habilidades: ["Torrent", "Rain Dish"],
    tipo: ["Água"],
    fraquezas: ["Elétrico", "Planta"],
    altura: 1.6,
    peso: 85.5,
    evolucao: "Wartortle",
  },
  {
    nome: "Garchomp",
    habilidades: ["Sand Veil", "Rough Skin"],
    tipo: ["Dragão", "Terra"],
    fraquezas: ["Gelo", "Dragão", "Fada"],
    altura: 1.9,
    peso: 95,
    evolucao: "Gabite",
  },
  {
    nome: "Aerodactyl",
    habilidades: ["Rock Head", "Pressure"],
    tipo: ["Rocha", "Voador"],
    fraquezas: ["Água", "Elétrico", "Gelo", "Rocha", "Aço"],
    altura: 1.8,
    peso: 59,
    evolucao: "Pupitar",
  },
  {
    nome: "Jolteon",
    habilidades: ["Volt Absorb", "Quick Feet"],
    tipo: ["Elétrico"],
    fraquezas: ["Terra"],
    altura: 0.8,
    peso: 24.5,
    evolucao: "Eevee",
  },
  {
    nome: "Arcanine",
    habilidades: ["Intimidate", "Flash Fire"],
    tipo: ["Fogo"],
    fraquezas: ["Água", "Terra", "Rocha"],
    altura: 1.9,
    peso: 155,
    evolucao: "Growlithe",
  },
  {
    nome: "Machoke",
    habilidades: ["Guts", "No Guard"],
    tipo: ["Lutador"],
    fraquezas: ["Voador", "Psíquico", "Fada"],
    altura: 1.5,
    peso: 70.5,
    evolucao: "Machop",
  },
  {
    nome: "Machop",
    habilidades: ["Guts", "No Guard"],
    tipo: ["Lutador"],
    fraquezas: ["Voador", "Psíquico", "Fada"],
    altura: 0.8,
    peso: 19.5,
    evolucao: "Machoke",
  },
  {
    nome: "Vaporeon",
    habilidades: ["Water Absorb", "Hydration"],
    tipo: ["Água"],
    fraquezas: ["Elétrico", "Planta"],
    altura: 1,
    peso: 29,
    evolucao: "Eevee",
  },
  {
    nome: "Golem",
    habilidades: ["Rock Head", "Sturdy"],
    tipo: ["Rocha", "Terra"],
    fraquezas: ["Água, Grama, Gelo, Lutador, Aço"],
    altura: 1.4,
    peso: 300,
    evolucao: "Graveler",
  },
  {
    nome: "Onix",
    habilidades: ["Rock Head", "Sturdy"],
    tipo: ["Rocha", "Terra"],
    fraquezas: ["Água, Grama, Gelo, Lutador, Aço"],
    altura: 8.8,
    peso: 210,
    evolucao: "Steelix",
  },
  {
    nome: "Lapras",
    habilidades: ["Water Absorb", "Shell Armor"],
    tipo: ["Água", "Gelo"],
    fraquezas: ["Lutador", "Elétrico", "Planta", "Pedra"],
    altura: 2.5,
    peso: 220,
    evolucao: "Lapras",
  },
  {
    nome: "Ditto",
    habilidades: ["Limber", "Imposter"],
    tipo: ["Normal"],
    fraquezas: ["Lutador"],
    altura: 0.3,
    peso: 4,
    evolucao: null,
  },
  {
    nome: "Vileplume",
    habilidades: ["Chlorophyll", "Effect Spore"],
    tipo: ["Planta", "Venenoso"],
    fraquezas: ["Fogo, Psíquico, Gelo, Voador"],
    altura: 1.2,
    peso: 18.6,
    evolucao: "Gloom",
  },
  {
    nome: "Ninetales",
    habilidades: ["Flash Fire", "Drought"],
    tipo: ["Fogo", "Gelo"],
    fraquezas: ["Água, Lutador, Rocha, Aço"],
    altura: 1.1,
    peso: 19.9,
    evolucao: null,
  },
  {
    nome: "Gyarados",
    habilidades: ["Intimidate", "Moxie"],
    tipo: ["Água", "Voador"],
    fraquezas: ["Elétrico", "Rocha"],
    altura: 6.5,
    peso: 235,
    evolucao: "Magikarp",
  },
  {
    nome: "Pidgeot",
    habilidades: ["Keen Eye", "Tangled Feet"],
    tipo: ["Normal", "Voador"],
    fraquezas: ["Elétrico", "Gelo", "Rocha"],
    altura: 1.5,
    peso: 39.5,
    evolucao: "Pidgeotto",
  },
  {
    nome: "Scyther",
    habilidades: ["Swarm", "Technician"],
    tipo: ["Inseto", "Voador"],
    fraquezas: ["Fogo", "Elétrico", "Gelo", "Pedra"],
    altura: 1.5,
    peso: 56,
    evolucao: "Scizor",
  },
  {
    nome: "Kadabra",
    habilidades: ["Synchronize", "Inner Focus"],
    tipo: ["Psíquico"],
    fraquezas: ["Inseto", "Fantasma", "Noturno"],
    altura: 1.3,
    peso: 56.5,
    evolucao: "Alakazam",
  },
  {
    nome: "Golem",
    habilidades: ["Rock Head", "Sturdy"],
    tipo: ["Rocha", "Terra"],
    fraquezas: ["Água", "Grama", "Gelo", "Lutador", "Aço"],
    altura: 1.4,
    peso: 300,
    evolucao: "Geodude",
  },
  {
    nome: "Machop",
    habilidades: ["Guts", "No Guard"],
    tipo: ["Lutador"],
    fraquezas: ["Voador", "Psíquico", "Fada"],
    altura: 0.8,
    peso: 19.5,
    evolucao: "Machoke",
  },
  {
    nome: "Vaporeon",
    habilidades: ["Water Absorb", "Hydration"],
    tipo: ["Água"],
    fraquezas: ["Elétrico", "Planta"],
    altura: 1.0,
    peso: 29,
    evolucao: "Eevee",
  },
  {
    nome: "Blastoise",
    habilidades: ["Torrent", "Rain Dish"],
    tipo: ["Água"],
    fraquezas: ["Elétrico", "Planta"],
    altura: 1.6,
    peso: 85.5,
    evolucao: "Wartortle",
  },
  {
    nome: "Arcanine",
    habilidades: ["Intimidate", "Flash Fire"],
    tipo: ["Fogo"],
    fraquezas: ["Água", "Terra", "Rocha"],
    altura: 1.9,
    peso: 155,
    evolucao: "Growlithe",
  },
  {
    nome: "Lapras",
    habilidades: ["Water Absorb", "Shell Armor"],
    tipo: ["Água", "Gelo"],
    fraquezas: ["Lutador", "Elétrico", "Planta", "Pedra"],
    altura: 2.5,
    peso: 220,
    evolucao: "None",
  },
  {
    nome: "Mewtwo",
    habilidades: ["Pressure", "Unnerve"],
    tipo: ["Psíquico"],
    fraquezas: ["Inseto", "Fantasma", "Noturno"],
    altura: 2.0,
    peso: 122,
    evolucao: "None",
  },
  {
    nome: "Aerodactyl",
    habilidades: ["Rock Head", "Pressure"],
    tipo: ["Rocha", "Voador"],
    fraquezas: ["Água", "Elétrico", "Gelo", "Rocha", "Aço"],
    altura: 1.8,
    peso: 59,
    evolucao: "None",
  },
  {
    nome: "Jolteon",
    habilidades: ["Volt Absorb", "Quick Feet"],
    tipo: ["Elétrico"],
    fraquezas: ["Terra"],
    altura: 0.8,
    peso: 24.5,
    evolucao: "Eevee",
  },
  {
    nome: "Gengar",
    habilidades: ["Levitate", "Cursed Body"],
    tipo: ["Fantasma", "Venenoso"],
    fraquezas: ["Psíquico", "Terra"],
    altura: 1.5,
    peso: 40.5,
    evolucao: "Haunter",
  },
  {
    nome: "Rhydon",
    habilidades: ["Lightning Rod", "Rock Head"],
    tipo: ["Terra", "Rocha"],
    fraquezas: ["Água", "Grama", "Gelo", "Lutador", "Terra", "Aço"],
    altura: 1.9,
    peso: 120,
    evolucao: "Rhyhorn",
  },
  {
    nome: "Machoke",
    habilidades: ["Guts", "No Guard"],
    tipo: ["Lutador"],
    fraquezas: ["Voador", "Psíquico", "Fada"],
    altura: 1.5,
    peso: 70.5,
    evolucao: "Machop",
  },
  {
    nome: "Pidgeotto",
    habilidades: ["Keen Eye", "Tangled Feet"],
    tipo: ["Normal", "Voador"],
    fraquezas: ["Elétrico", "Gelo", "Rocha"],
    altura: 1.1,
    peso: 30,
    evolucao: "Pidgey",
  },
  {
    nome: "Venusaur",
    habilidades: ["Overgrow", "Chlorophyll"],
    tipo: ["Planta", "Venenoso"],
    fraquezas: ["Fogo", "Psíquico", "Gelo", "Voador"],
    altura: 2.0,
    peso: 100,
    evolucao: "Ivysaur",
  },
  {
    nome: "Gyarados",
    habilidades: ["Intimidate", "Moxie"],
    tipo: ["Água", "Voador"],
    fraquezas: ["Elétrico", "Rocha"],
    altura: 6.5,
    peso: 235,
    evolucao: "Magikarp",
  },
];
